# Project-wide Gradle settings.

# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.

# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

# AAB / Release optimization
android.experimental.enableNewResourceShrinker=true

# R8 full mode
android.enableR8.fullMode=true

# Keep Gradle daemon alive between builds for speed
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=true

# Memory
org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8

# AndroidX
android.useAndroidX=true

org.gradle.java.installations.auto-download=true
org.gradle.java.installations.paths=C\:\\Users\\Dimitri\\AppData\\Local\\Temp\\jdk21\\jdk-21.0.12.1+1

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
